["Org: aircause", " Name: NFxyz.16", " Modal No: akso16", " Date: 13/09/16", " Kinnect scan", " view: ceiling to ground", " Image: chairs and obsticles floor data removed "], 
["Org: aircause", " Name: NFxyz.18", " Modal No: akso18", " Date: 13/09/16", " Kinnect scan", " view: ceiling to ground", " Image: chairs and obsticles floor data removed "], 
["Org: aircause", " Name: NFxyz.20", " Modal No: akso20", " Date: 13/09/16", " Kinnect scan", " view: ceiling to ground", " Image: chairs and obsticles floor data removed "], 
["Org: aircause", " Name: NFxyz.30", " Modal No: akso30", " Date: 13/09/16", " Kinnect scan", " view: ceiling to ground", " Image: chairs and obsticles floor data removed "], 
["Org: aircause", " Name: xyz.30", " Modal No: akso30", " Date: 13/09/16", " Kinnect scan", " view: ceiling to ground", " Image: chairs and obsticles "], 
["Org: aircause", " Name: xyz.festo.01", " Modal No: aksF01", " Date: 10/10/16", " Kinnect scan", " view:side of factory", " Image: factory "], 
["Org: aircause", " Name: xyz.festo.02", " Modal No: aksF02", " Date: 10/10/16", " Kinnect scan", " view:side of factory", " Image: factory "], 
["Org: aircause", " Name: xyz.festo.03", " Modal No: aksoF03", " Date: 10/10/16", " Kinnect scan", " view:side of factory", " Image: factory "], 
